#!/bin/bash

#################################################################################################################
# Usage:
#        ./genlog
# Note:
#	 extract syslog from disk
#
# BUGS:
#                                                                                                 Forrest Y. Yu
#                                                                                                 Nov. 21, 2008
#################################################################################################################

echo
echo "[syslog]"
echo "--------"
syslog_tmp_file=/tmp/prntdisk.tmp
syslog_file=/root/oranges-os/chapter9/f/scripts/llsyslog
sudo dd if=/root/bochs/bin/80m.img of=$syslog_tmp_file bs=1 count=32 skip=`echo "obase=10;ibase=16;1C88000" | bc` 2> /dev/null
sudo dd if=/root/bochs/bin/80m.img of=$syslog_file bs=1 count=`head -n 1 $syslog_tmp_file | sed 's/\ //g'` skip=`echo "obase=10;ibase=16;1C88000" | bc` 2> /dev/null
echo >> $syslog_file
echo "time: "`cat $syslog_file | head -n 3 | tail -n 1`
echo
cat $syslog_file | sed '1,3d' > filedesc.dot
cat filedesc.dot | sh splitgraphs
echo

exit 0

